version: 2.1

orbs:
  architect: giantswarm/architect@5.11.5

workflows:
  test:
    jobs:
      - architect/go-build:
          name: go-build
          binary: upgrade-schedule-operator
          filters:
            tags:
              only: /^v.*/
      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          requires:
            - go-build
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          context: "architect"
          name: push-upgrade-schedule-operator-to-app-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "upgrade-schedule-operator"
          requires:
            - push-to-registries
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: "architect"
          name: push-upgrade-schedule-operator-to-aws-app-collection
          app_name: "upgrade-schedule-operator"
          app_collection_repo: "aws-app-collection"
          requires:
            - push-upgrade-schedule-operator-to-app-catalog
          filters:
            # Only do this when a new tag is created.
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: "architect"
          name: push-upgrade-schedule-operator-to-azure-app-collection
          app_name: "upgrade-schedule-operator"
          app_collection_repo: "azure-app-collection"
          requires:
            - push-upgrade-schedule-operator-to-app-catalog
          filters:
            # Only do this when a new tag is created.
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-to-capa-app-collection
          app_name: "upgrade-schedule-operator"
          app_collection_repo: "capa-app-collection"
          requires:
            - push-upgrade-schedule-operator-to-app-catalog
            - push-to-registries
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-to-capz-app-collection
          app_name: "upgrade-schedule-operator"
          app_collection_repo: "capz-app-collection"
          requires:
            - push-upgrade-schedule-operator-to-app-catalog
            - push-to-registries
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
