version: 2.1

orbs:
  architect: giantswarm/architect@4.33.0

workflows:
  test:
    jobs:
      - architect/go-build:
          name: go-build
          binary: upgrade-schedule-operator
          filters:
            tags:
              only: /^v.*/
      - architect/push-to-docker:
          context: "architect"
          name: push-upgrade-schedule-operator-to-docker
          image: "docker.io/giantswarm/upgrade-schedule-operator"
          username_envar: "DOCKER_USERNAME"
          password_envar: "DOCKER_PASSWORD"
          requires:
            - go-build
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          context: "architect"
          name: push-upgrade-schedule-operator-to-quay
          image: "quay.io/giantswarm/upgrade-schedule-operator"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - go-build
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          context: "architect"
          name: push-upgrade-schedule-operator-to-aliyun
          image: "giantswarm-registry.cn-shanghai.cr.aliyuncs.com/giantswarm/upgrade-schedule-operator"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          requires:
            - go-build
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          context: "architect"
          name: push-upgrade-schedule-operator-to-app-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "upgrade-schedule-operator"
          requires:
            - push-upgrade-schedule-operator-to-docker
            - push-upgrade-schedule-operator-to-quay
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: "architect"
          name: push-upgrade-schedule-operator-to-aws-app-collection
          app_name: "upgrade-schedule-operator"
          app_collection_repo: "aws-app-collection"
          requires:
            - push-upgrade-schedule-operator-to-app-catalog
          filters:
            # Only do this when a new tag is created.
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: "architect"
          name: push-upgrade-schedule-operator-to-azure-app-collection
          app_name: "upgrade-schedule-operator"
          app_collection_repo: "azure-app-collection"
          requires:
            - push-upgrade-schedule-operator-to-app-catalog
          filters:
            # Only do this when a new tag is created.
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
