project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"
image:
  name: "giantswarm/upgrade-schedule-operator"
  tag: "[[ .Version ]]"
registry:
  domain: gsoci.azurecr.io

installation:
  name: name

pod:
  user:
    id: 1000
  group:
    id: 1000

verticalPodAutoscaler:
  enabled: true

# Add seccomp to pod security context
podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

# Add seccomp to container security context
securityContext:
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop:
      - ALL

global:
  podSecurityStandards:
    enforced: false
